### ISSUE TITLE
[Bug] Server does not automatically create `Client` folder, inside `Resources` on first run

### ISSUE THREAD

**Issue by Mack29446** [BeamMP/BeamMP-Server#149] opened 2022-11-11 15:53 UTC
**Fill out general information**
OS: Linux, Docker Debian
BeamMP-Server Version: 3.1.1

**Describe the bug**
The server does not automatically make the `Client` folder within `Resources`, but it does create the `Server` folder, when run for the first time

**To Reproduce**
1. Setup a new server in a clean directory
2. Observe that the Client folder is not created
3. Run the server a second time, the folder will be created

**Expected behavior**
Both a Client and Server folder are created on the first run

**Comment by lionkor** [comment] 2022-11-11 19:59
I can't reproduce this, can someone else please confirm this?

Note that when the server complains about a key, it will not generate any folders.

**Comment by lionkor** [comment] 2024-05-11 10:26
No more info, closing

**Closed as not planned by lionkor** 2024-05-11 10:26 UTC
Labels: bug
